In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', 80)

import random

import time

import sys
sys.path.append("../")

from src.object import *
from src.create import *

from config.formation import *

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
df_name = pd.read_csv("../data/csv/NationalNames.csv")
df_name_list = list(df_name[df_name.Gender=='M'].Name.sample(500))

In [3]:
df_place = pd.read_csv("../data/csv/results.csv")
df_place = df_place.city.unique()

In [4]:
league_team = []

for i in range(20):
    min_rate = np.random.randint(70, 78)
    max_rate = min_rate + 15
    players = random_create_players(27, 3, min_rate, max_rate, df_name_list)
    formation = random_create_formation()
    A = Team(name=df_place[i], 
             formation=formation)
    A.affilation_players = players
    
    league_team.append(A)

L1 = League(name="premia", 
            teams=league_team,
            num=20,
            category='top',
            relegation_num=3)

In [5]:
league_team = []

for i in range(20):
    min_rate = np.random.randint(60, 70)
    max_rate = min_rate + 15
    players = random_create_players(27, 3, min_rate, max_rate, df_name_list)
    formation = random_create_formation()
    A = Team(name=df_place[i+20], formation=formation)
    A.affilation_players = players
    
    league_team.append(A)

L2 = League(name="championship",
            teams=league_team,
            num=20,
            category='lowest',
            relegation_num=0,
            promotion_num=3)

In [6]:
year = 1990

England = ProSoccerLeague(name="england", leagues=[L1, L2])

for year in range(1990, 1991):
    print(year)
    competition = Competition(name=f"FA杯_{year}")

    England.play_1season(year, competition)

1990

100%|███████████████████████████████████████████████████████████████████████████████████| 38/38 [00:14<00:00,  2.64it/s]

In [7]:
England.leagues[0].player_result["premia_1990"].sort_values("goal")

           名前 ポジション     リーグ    年度         チーム 試合数 goal assist   分類
398   Merrell    RB  premia  1990     Swansea   4    0      0  リーグ
156   Kendale    LW  premia  1990  Manchester   5    0      0  リーグ
157    Braden    LW  premia  1990  Manchester   4    0      0  リーグ
367     Avian   CDM  premia  1990    Richmond  31    0      4  リーグ
160      Norm    RB  premia  1990  Manchester   2    0      0  リーグ
..        ...   ...     ...   ...         ...  ..  ...    ...  ...
39    Dorothy    ST  premia  1990      London  29   15      0  リーグ
204      Jori    ST  premia  1990       Crewe  24   15      0  リーグ
393    Walton    ST  premia  1990     Swansea  38   23      6  リーグ
358       Khi    ST  premia  1990    Richmond  38   25      5  リーグ
323  Cheyenne    ST  premia  1990      Bangor  38   25      3  リーグ

[399 rows x 9 columns]

In [8]:
England.leagues[0].teams[0].affilation_players_all_rate

,ST,CF,CAM,RW,LW,RM,LM,CM,CDM,RB,LB,CB,RWB,LWB,injury,partification
0,65,58,58,60,60,60,60,56,65,68,68,74,69,69,0,0
1,72,72,72,79,79,73,73,70,69,76,76,70,73,73,10,0
2,71,69,69,76,76,71,71,67,73,78,78,78,77,77,0,1
3,75,66,66,69,69,68,68,61,60,68,68,61,69,69,0,1
4,67,63,63,75,75,65,65,58,57,70,70,59,67,67,0,1
5,63,60,60,75,75,62,62,55,58,71,71,61,66,66,0,0
6,65,56,56,62,62,59,59,53,69,72,72,83,71,71,13,0
7,58,64,64,73,73,65,65,65,65,68,68,62,64,64,0,0
8,56,54,54,55,55,56,56,56,67,62,62,75,62,62,0,0
9,73,65,65,76,76,67,67,58,58,70,70,60,67,67,0,1
10,74,68,68,71,71,68,68,64,65,70,70,67,70,70,6,0
11,76,60,60,53,53,58,58,54,61,57,57,67,58,58,0,0
12,56,59,59,56,56,59,59,63,72,62,62,77,62,62,0,0
13,54,57,57,63,63,61,61,61,70,72,72,78,73,73,0,1
14,62,68,68,69,69,68,68,72,74,72,72,73,73,73,-1,1
15,79,68,68,70,70,68,68,63,73,74,74,82,72,72,0,1
16,66,61,61,61,61,62,62,60,68,67,67,75,67,67,0,0
17,70,73,73,73,73,73,73,73,66,71,71,61,73,73,0,1
18,74,69,69,77,77,72,72,65,65,78,78,69,78,78,2,0
19,67,78,78,87,87,80,80,80,70,80,80,64,79,79,3,0
20,73,70,70,60,60,70,70,71,73,67,67,75,72,72,0,1
21,70,74,74,79,79,76,76,74,70,77,77,68,77,77,1,0
22,54,56,56,57,57,59,59,60,68,67,67,73,71,71,0,0
23,82,74,74,70,70,72,72,71,74,69,69,76,67,67,8,0
24,62,73,73,87,87,75,75,72,59,75,75,50,72,72,13,0
25,67,65,65,73,73,66,66,61,60,68,68,61,64,64,0,0
26,67,57,57,54,54,58,58,56,71,65,65,83,66,66,0,1

In [9]:
England.leagues[0].teams[0].affilation_players_all_rate

,ST,CF,CAM,RW,LW,RM,LM,CM,CDM,RB,LB,CB,RWB,LWB,injury,partification
0,65,58,58,60,60,60,60,56,65,68,68,74,69,69,0,0
1,72,72,72,79,79,73,73,70,69,76,76,70,73,73,10,0
2,71,69,69,76,76,71,71,67,73,78,78,78,77,77,0,1
3,75,66,66,69,69,68,68,61,60,68,68,61,69,69,0,1
4,67,63,63,75,75,65,65,58,57,70,70,59,67,67,0,1
5,63,60,60,75,75,62,62,55,58,71,71,61,66,66,0,0
6,65,56,56,62,62,59,59,53,69,72,72,83,71,71,13,0
7,58,64,64,73,73,65,65,65,65,68,68,62,64,64,0,0
8,56,54,54,55,55,56,56,56,67,62,62,75,62,62,0,0
9,73,65,65,76,76,67,67,58,58,70,70,60,67,67,0,1
10,74,68,68,71,71,68,68,64,65,70,70,67,70,70,6,0
11,76,60,60,53,53,58,58,54,61,57,57,67,58,58,0,0
12,56,59,59,56,56,59,59,63,72,62,62,77,62,62,0,0
13,54,57,57,63,63,61,61,61,70,72,72,78,73,73,0,1
14,62,68,68,69,69,68,68,72,74,72,72,73,73,73,-1,1
15,79,68,68,70,70,68,68,63,73,74,74,82,72,72,0,1
16,66,61,61,61,61,62,62,60,68,67,67,75,67,67,0,0
17,70,73,73,73,73,73,73,73,66,71,71,61,73,73,0,1
18,74,69,69,77,77,72,72,65,65,78,78,69,78,78,2,0
19,67,78,78,87,87,80,80,80,70,80,80,64,79,79,3,0
20,73,70,70,60,60,70,70,71,73,67,67,75,72,72,0,1
21,70,74,74,79,79,76,76,74,70,77,77,68,77,77,1,0
22,54,56,56,57,57,59,59,60,68,67,67,73,71,71,0,0
23,82,74,74,70,70,72,72,71,74,69,69,76,67,67,8,0
24,62,73,73,87,87,75,75,72,59,75,75,50,72,72,13,0
25,67,65,65,73,73,66,66,61,60,68,68,61,64,64,0,0
26,67,57,57,54,54,58,58,56,71,65,65,83,66,66,0,1

In [10]:
England.leagues[0].teams[0].affilation_players_gk_rate

   GK
0  76
1  84
2  79

In [11]:
England.leagues[0].teams[0].affilation_players_gk_rate

   GK
0  76
1  84
2  79